export const userPath = (userId: string) => `users/${userId}`;
export const novabeautyUserPath = (userId: string) => `novabeautyUsers/${userId}`;
export const profilePath = (userId: string) => `novabeautyUsers/${userId}/profile/main`;
export const settingsPath = (userId: string) => `novabeautyUsers/${userId}/settings/main`;
export const clientsPath = (userId: string) => `novabeautyUsers/${userId}/clients`;
export const servicesPath = (userId: string) => `novabeautyUsers/${userId}/services`;
export const appointmentsPath = (userId: string) => `novabeautyUsers/${userId}/appointments`;
export const productsPath = (userId: string) => `novabeautyUsers/${userId}/products`;
export const profileImagePath = (userId: string) => `novabeautyUsers/${userId}/profile/profile.jpg`;
